### PR TITLE
Initial attempt at Python 3 support

### PR DESCRIPTION
**Pull request by jni**
Hi all,

I don't have a working version of vigra on my computer, so I can't test this, but it probably gets you most or all of the way towards supporting both Python 2 and 3, while adding only `six` as a dependency. (This is a very common, pure-python package, so I don't think it's a big dependency to have.)

Please let me know in the comments if there are any test failures, and I will do my best to address them!

### CODE REVIEW

**Comment by rhoef** [comment]
Thanks for your effort!

Currently we do not work on a python 3 port. Since the latest official vigra is ported to python3 it will become an issue. We also need to port cecogs c++ extension. 
Anyway I'll test the changes for python 2.

**Comment by jni** [comment]
Hi @rhoef!

Ah, I didn't realise there was a C++ extension. How are the bindings written? If Cython, things should Just Work. Otherwise... Well, yes, definitely, it might be time to shelf this to revisit at a later date. =)

I saw vigra (+libtiff) as your only dependency, and I knew that it's Py3 compatible now, so I thought this might be an easy job. Let me know if you run into trouble!

**Comment by rhoef** [comment]
we use boost python. Basically there should be not much work to do, only linking against the boost_python-3.x. 

Unfortunately the code condition is not ideal. Lots of warnings. Some changes in the numpy API will cause errors. etc...
It will be for sure more time consuming.

**Comment by jni** [comment]
What do you mean by "the code condition"? C++, or my (admittedly automated, but sanity checked) mods?

I'm very happy to contribute, with some guidance.

**Comment by jni** [comment]
(But I would like to avoid building C things. =P)

**Comment by rhoef** [comment]
If you build the extension  you'll get  a lot of template warnings. Most come from type comparison (unsigend vs int) or unused variables.  Since it is template code the compiler output is large and hard to read.
You need to have at least boost python linked against python 3, and vigranumpy linked against python 3

vigranumpy could be replaced by skimage. It is mostly used for io and basic operations such as resampling an image. That might be less time consuming than compiling vigra python bindings.

What platform do you use. On Linux boost python is probably included in the package management system

**Comment by jni** [comment]
Hi @rhoef!

Sorry for long gap in response, was at PyCon AU. =)

Depending on the amount of glue code, Boost Python might also be replaceable with Cython without too much effort. The nice thing is that Cython gives you Py2/3 compatibility "for free". At any rate I believe Boost-Python3 is in conda-forge, headers and all.

I'll have a look at vigranumpy uses in the next few days.

Thanks!

**Comment by rhoef** [comment]
Hi,
I'm not sure if replacing boost by cython is convenient right now. Basically you need to replace the ```boost_python.so``` by ```boost_python_34.so``` in the setup.py file.  The c++ code is not touched (except issue 2. below)

There are two issues:
1. compile boost_python - I use linux, so it is in the packages, windows is more tricky but well documented
2. numpy will raise some compile errors and warnings which are introduced by then new python3 API. But it can be fixed easily.

Heres an example how the exention might be setup in the setup.py file
```
extension = Extension('cecog._cecog',
                  sources = [join('src', 'cecog.cxx')],
                  include_dirs=INCLUDES,
                  libraries=['boost_python-py34', 'tiff', 'vigraimpex'],
                  extra_compile_args = ['-O3', '-fPIC', '-std=c++11'],
                  language = 'c++')
```

**Comment by jni** [comment]
Hi folks, this PR is outdated and it looks like the package is no longer maintained, so I'm going to close it. Thanks for the consideration back in the day! 😅

**Pull request closed without merging**
